import 'package:ebook/core/resources/routes_manager.dart';

import 'entities/student.dart';
import 'resources/assets_manager.dart';

abstract class AppConstants {
  static const List homeImagesList = [
    SvgAssets.progress,
    SvgAssets.assignment,
    SvgAssets.studentActivities,
    SvgAssets.audioRead,
    SvgAssets.comparePerformance,
    SvgAssets.learningStyles,
    SvgAssets.classRoom,
    SvgAssets.messages,
    SvgAssets.browseContent,
    SvgAssets.training,
  ];

  static const List homeScreensList = [
    Routes.teacherProgressRoute,
    Routes.teacherAssignmentRoute,
    Routes.teacherStudentActivitiesRoute,
    Routes.teacherAudioReadingRoute,
    Routes.teacherComparePerformanceRoute,
    Routes.teacherLearningStylesRoute,
    Routes.teacherClassroomRoute,
    Routes.teacherMessagesRoute,
    Routes.booksRoute,
    Routes.teacherTrainingRoute,
  ];

  static const List homeTitlesList = [
    "progress",
    "assignments",
    "student_activities",
    "audio_reading",
    "compare_performance",
    "learning_styles",
    "classroom",
    "my_messages",
    "browse_content",
    "training",
  ];

  static const List<String> bookLevelImages = [
    ImageAssets.charA,
    ImageAssets.charB,
    ImageAssets.charC,
    ImageAssets.charD,
    ImageAssets.charE,
    ImageAssets.charF,
    ImageAssets.charG,
    ImageAssets.charI,
    ImageAssets.charJ,
    ImageAssets.charK,
    ImageAssets.charL,
    ImageAssets.charM,
    ImageAssets.charN,
    ImageAssets.charO,
    ImageAssets.charP,
    ImageAssets.charQ,
    ImageAssets.charR,
    ImageAssets.charS,
  ];
  static const List<Student> dummyStudentsData = [
    Student(
      name: 'Ali Ahmed',
      allAssignments: 10,
      completedAssignments: 5,
      remainingAssignments: 5,
      readingAssignments: 5,
      completedReadingAssignments: 5,
      listeningAssignments: 5,
      completedListeningAssignments: 5,
      tests: 5,
      completedTests: 5,
      numberOfTasks: 4,
      completedTasks: 8,
      remainingTasks: 9,
    ),
    Student(
      name: 'Mohamed Ibrahim',
      allAssignments: 10,
      completedAssignments: 5,
      remainingAssignments: 5,
      readingAssignments: 5,
      completedReadingAssignments: 5,
      listeningAssignments: 5,
      completedListeningAssignments: 5,
      tests: 5,
      completedTests: 5,
      numberOfTasks: 4,
      completedTasks: 8,
      remainingTasks: 9,
    ),
    Student(
      name: 'Ahmed Ali',
      allAssignments: 10,
      completedAssignments: 5,
      remainingAssignments: 5,
      readingAssignments: 5,
      completedReadingAssignments: 5,
      listeningAssignments: 5,
      completedListeningAssignments: 5,
      tests: 5,
      completedTests: 5,
      numberOfTasks: 4,
      completedTasks: 8,
      remainingTasks: 9,
    ),
    Student(
      name: 'Ibrahim Mohamed',
      allAssignments: 10,
      completedAssignments: 5,
      remainingAssignments: 5,
      readingAssignments: 5,
      completedReadingAssignments: 5,
      listeningAssignments: 5,
      completedListeningAssignments: 5,
      tests: 5,
      completedTests: 5,
      numberOfTasks: 4,
      completedTasks: 8,
      remainingTasks: 9,
    ),
    Student(
      name: 'Ali Ahmed',
      allAssignments: 10,
      completedAssignments: 5,
      remainingAssignments: 5,
      readingAssignments: 5,
      completedReadingAssignments: 5,
      listeningAssignments: 5,
      completedListeningAssignments: 5,
      tests: 5,
      completedTests: 5,
      numberOfTasks: 4,
      completedTasks: 8,
      remainingTasks: 9,
    ),
    Student(
      name: 'Mohamed Ibrahim',
      allAssignments: 10,
      completedAssignments: 5,
      remainingAssignments: 5,
      readingAssignments: 5,
      completedReadingAssignments: 5,
      listeningAssignments: 5,
      completedListeningAssignments: 5,
      tests: 5,
      completedTests: 5,
      numberOfTasks: 4,
      completedTasks: 8,
      remainingTasks: 9,
    ),
    Student(
      name: 'Ahmed Ali',
      allAssignments: 10,
      completedAssignments: 5,
      remainingAssignments: 5,
      readingAssignments: 5,
      completedReadingAssignments: 5,
      listeningAssignments: 5,
      completedListeningAssignments: 5,
      tests: 5,
      completedTests: 5,
      numberOfTasks: 4,
      completedTasks: 8,
      remainingTasks: 9,
    ),
    Student(
      name: 'Ibrahim Mohamed',
      allAssignments: 10,
      completedAssignments: 5,
      remainingAssignments: 5,
      readingAssignments: 5,
      completedReadingAssignments: 5,
      listeningAssignments: 5,
      completedListeningAssignments: 5,
      tests: 5,
      completedTests: 5,
      numberOfTasks: 4,
      completedTasks: 8,
      remainingTasks: 9,
    ),
    Student(
      name: 'Ali Ahmed',
      allAssignments: 10,
      completedAssignments: 5,
      remainingAssignments: 5,
      readingAssignments: 5,
      completedReadingAssignments: 5,
      listeningAssignments: 5,
      completedListeningAssignments: 5,
      tests: 5,
      completedTests: 5,
      numberOfTasks: 4,
      completedTasks: 8,
      remainingTasks: 9,
    ),
    Student(
      name: 'Mohamed Ibrahim',
      allAssignments: 10,
      completedAssignments: 5,
      remainingAssignments: 5,
      readingAssignments: 5,
      completedReadingAssignments: 5,
      listeningAssignments: 5,
      completedListeningAssignments: 5,
      tests: 5,
      completedTests: 5,
      numberOfTasks: 4,
      completedTasks: 8,
      remainingTasks: 9,
    ),
  ];
}
